version: "3.1"

services:
  db:
    image: mysql:8.2.0
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: Asia/Tokyo
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
